### ISSUE TITLE
SQL gives different result set between VS code / ACS / greenscren

### ISSUE THREAD

**Issue by dev-wouter** [worksofliam/node-db2fori#2]
hi, 

when trying only to use VS-Code i stumbled on something strange.
when looking at 1 date field the result set  in VS code shows null, but actually it is *loval date.
even when i have a where 'Is not null' it still gives the *loval fields in the result set. 

i think VS code makes the *loval value to a null in the result set but the query does not translate Null to *loval

![image](https://github.com/user-attachments/assets/e2b11fab-a8ba-4fe7-b20c-b6eae04bd52c)

if needed more info you can always ask.

Ps. working on the latest releases of the plugins/ vs code

**Comment by worksofliam** [comment]
@dev-wouter I think you have the wrong repo. You want codefori/vscode-db2i.
